const $=id=>document.getElementById(id);
const RULES=["Transparency","People first","Fair play","Family first","Supportive prototyping"];
function nowClock(){$("clock").textContent=new Date().toLocaleTimeString("en-CA",{hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"America/Vancouver"})}
function boot(){const lines=["INITIALIZING CORE","LOADING PILLARS","FAMILY FIRST ARMED","SYSTEM ONLINE"];let i=0;const tick=setInterval(()=>{$("boot-sub").textContent=lines[i];i++;if(i>=lines.length){clearInterval(tick);setTimeout(()=>{$("boot").style.display="none";$("app").hidden=false;greet();drawViz()},420)}},380)}
function setScreen(name){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));document.querySelectorAll(".dock-btn").forEach(b=>b.classList.toggle("active",b.dataset.screen===name));$("screen-"+name).classList.add("active")}
function addMsg(role,text,meta){const wrap=document.createElement("div");wrap.className="msg "+role;wrap.innerHTML=`<div class="who">${role==="user"?"MIKE":"JARVIS"}</div><div class="bubble"></div>${meta?"<div class=\"triage\"></div>":""}`;wrap.querySelector(".bubble").textContent=text;if(meta)wrap.querySelector(".triage").textContent=meta;$("log").appendChild(wrap);$("log").scrollTop=$("log").scrollHeight}
function greet(){addMsg("jarvis","Online. Dispatcher ready.\nFamily · Work · Business · Personal.","TRIAGE standby · PRIORITY family")}
function pillarOf(t){t=t.toLowerCase();if(/(kid|child|school|wife|family|daughter|son|pickup)/.test(t))return"Family";if(/(payroll|hire|staff|team|morale|shop|job)/.test(t))return"Work";if(/(quote|client|revenue|deal|invoice|business)/.test(t))return"Business";return"Personal"}
function dispatch(text){const pillar=pillarOf(text);const t=text.toLowerCase();const clash=/(deadline|meeting|call|shift|quote)/.test(t)&&pillar==="Family";let reply;if(clash)reply="Family first. Attend the personal event.\nCover the business item with a deputy, a slip, or a short pilot.";else if(/(cheat|loophole|lie|cover.?up)/.test(t))reply="Rejected. Fair play and transparency stand.";else if(/(bet the shop|layoff to grow)/.test(t))reply="People first. Pilot it small or do not do it.";else if(/(should i|what do i|help me|plan)/.test(t))reply="Low-risk pilot: one next action, one owner, one review date.";else reply="Logged against "+pillar+". Next move: one concrete action.";return{reply,meta:`PILLAR ${pillar} · PRIORITY ${pillar==="Family"?"CRITICAL":"NORMAL"}`,pillar}}
function send(text){const clean=text.trim();if(!clean)return;setScreen("dispatch");addMsg("user",clean);$("input").value="";const {reply,meta,pillar}=dispatch(clean);$("status-line").textContent=pillar+" in focus. Family still outranks money.";setTimeout(()=>addMsg("jarvis",reply,meta),280)}
function drawViz(){const c=$("viz");const ctx=c.getContext("2d");const dpr=Math.min(devicePixelRatio||1,2);const w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);let t=0;function frame(){ctx.clearRect(0,0,w,h);ctx.strokeStyle="rgba(122,212,240,0.18)";const cx=w/2,cy=h/2+8;for(let i=1;i<=4;i++){ctx.beginPath();ctx.arc(cx,cy,18*i+Math.sin(t/20+i)*3,0,Math.PI*2);ctx.stroke()}ctx.beginPath();ctx.strokeStyle="rgba(122,212,240,0.55)";const sweep=(t/40)%(Math.PI*2);ctx.arc(cx,cy,54,sweep,sweep+.8);ctx.stroke();ctx.fillStyle="#7ad4f0";ctx.beginPath();ctx.arc(cx,cy,3.2,0,Math.PI*2);ctx.fill();t++;requestAnimationFrame(frame)}frame()}
function setupVoice(){const Rec=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Rec){$("mic").addEventListener("click",()=>addMsg("jarvis","Voice not available here. Use Safari.","SYSTEM"));return}const rec=new Rec();rec.lang="en-CA";rec.onresult=e=>send(e.results[0][0].transcript);rec.onend=()=>$("mic").classList.remove("hot");$("mic").addEventListener("click",()=>{$("mic").classList.add("hot");rec.start()})}
document.querySelectorAll(".dock-btn").forEach(b=>b.addEventListener("click",()=>setScreen(b.dataset.screen)));document.querySelectorAll(".pillar").forEach(b=>b.addEventListener("click",()=>{setScreen("dispatch");send("Status on "+b.dataset.pillar)}));$("composer").addEventListener("submit",e=>{e.preventDefault();send($("input").value)});nowClock();setInterval(nowClock,1000);setupVoice();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});boot();
