const $ = (id) => document.getElementById(id);
const KEY_STORE = "jarvis.xai.key";
const MODEL_STORE = "jarvis.xai.model";
const API = "https://api.x.ai/v1/chat/completions";
const SYSTEM = `You are J.A.R.V.I.S., Central Dispatcher for Mike Brown in Surrey, British Columbia.\n\nLife pillars: Family, Work, Business, Personal.\n\nCore rules:\n1. Transparency \u2014 immediate honest disclosure on failures. No cover-ups.\n2. People First \u2014 team security, job preservation, and morale over high-risk growth.\n3. Fair Play \u2014 reject loopholes, unlisted data, and unethical advantages.\n4. Family First \u2014 family emergencies and personal well-being outrank business and money.\n5. Supportive Prototyping \u2014 recommend low-risk pilots instead of rejecting ideas.\n\nProtocol:\n- Start with a one-line triage: INTENT / PILLAR / PRIORITY.\n- Then answer. Calm, precise, objective, executive. No filler.\n- If deep work is needed, add a handoff: Target Bot, Objective, Context, Output Style.\n- Timezone: America/Vancouver.`;
const RULES = ["Transparency","People first","Fair play","Family first","Supportive prototyping"];
const history = [];
function getKey(){return localStorage.getItem(KEY_STORE)||""}
function getModel(){return localStorage.getItem(MODEL_STORE)||"grok-4.6"}
function hasBrain(){return getKey().length>8}
function paintBrain(){const live=hasBrain();const pill=$("brain-pill");pill.classList.toggle("local",!live);pill.lastChild.textContent=live?" GROK":" LOCAL";$("runtime-dd").textContent=live?"Grok "+getModel():"Local fallback";$("cloud-dd").textContent=live?"Live · key on device":"Grok · needs key";$("brain-note").textContent=live?"Brain live. Key stored only in this browser.":"No key saved. Local rules only.";$("status-line").textContent=live?"Grok online. Family first.":"Four pillars nominal. Brain offline until a key is saved.";$("api-key").value=getKey();$("model").value=getModel()}
function nowClock(){$("clock").textContent=new Date().toLocaleTimeString("en-CA",{hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"America/Vancouver"})}
function boot(){const lines=["INITIALIZING CORE","LOADING PILLARS","FAMILY FIRST ARMED","LINKING GROK","SYSTEM ONLINE"];let i=0;const tick=setInterval(()=>{$("boot-sub").textContent=lines[i];i+=1;if(i>=lines.length){clearInterval(tick);setTimeout(()=>{$("boot").style.display="none";$("app").hidden=false;paintBrain();greet();drawViz()},420)}},320)}
function setScreen(name){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));document.querySelectorAll(".dock-btn").forEach(b=>b.classList.toggle("active",b.dataset.screen===name));$("screen-"+name).classList.add("active");if(name==="dispatch")$("input").focus()}
function addMsg(role,text,meta){const wrap=document.createElement("div");wrap.className="msg "+role;wrap.innerHTML=`<div class="who">${role==="user"?"MIKE":"JARVIS"}</div><div class="bubble"></div>`+(meta?`<div class="triage"></div>`:"");wrap.querySelector(".bubble").textContent=text;if(meta)wrap.querySelector(".triage").textContent=meta;$("log").appendChild(wrap);$("log").scrollTop=$("log").scrollHeight;return wrap}
function greet(){addMsg("jarvis",hasBrain()?"Grok linked. Dispatcher ready.\nFamily · Work · Business · Personal.":"Online on local rules. Save an xAI key under System to go live.",hasBrain()?"BRAIN grok · PRIORITY family":"BRAIN local · PRIORITY family")}
function pillarOf(text){const t=text.toLowerCase();if(/(kid|child|school|wife|family|daughter|son|home dinner|pickup)/.test(t))return"Family";if(/(payroll|hire|staff|team|morale|shop|job)/.test(t))return"Work";if(/(quote|client|revenue|deal|cans|container|invoice|business)/.test(t))return"Business";if(/(sleep|gym|health|personal|tired|doctor)/.test(t))return"Personal";return"Personal"}
function localDispatch(text){const pillar=pillarOf(text);const t=text.toLowerCase();const clash=/(deadline|meeting|call|shift|quote)/.test(t)&&pillar==="Family";let reply;if(clash)reply="Family first. Attend the personal event.\nCover the business item with a deputy, a slip, or a short pilot.";else if(/(cheat|loophole|scrape unlisted|lie|cover.?up)/.test(t))reply="Rejected. Fair play and transparency stand.";else if(/(risk everything|bet the shop|layoff to grow)/.test(t))reply="People first. Pilot it small or do not do it.";else if(/(should i|what do i|help me|plan)/.test(t))reply="Low-risk pilot: one next action, one owner, one review date.";else reply="Logged against "+pillar+". Next move: one concrete action.";return{reply,meta:`BRAIN local\nPILLAR ${pillar}`,pillar}}
async function grokDispatch(text){const messages=[{role:"system",content:SYSTEM},...history.slice(-16),{role:"user",content:text}];const res=await fetch(API,{method:"POST",headers:{Authorization:"Bearer "+getKey(),"Content-Type":"application/json"},body:JSON.stringify({model:getModel(),messages,temperature:0.4})});const body=await res.json().catch(()=>({}));if(!res.ok){const err=body.error&&body.error.message||body.error||res.status+" "+res.statusText;throw new Error(String(err))}const reply=(body.choices&&body.choices[0]&&body.choices[0].message&&body.choices[0].message.content||"").trim();if(!reply)throw new Error("Empty model response.");history.push({role:"user",content:text});history.push({role:"assistant",content:reply});return{reply,meta:`BRAIN ${getModel()}\nPILLAR ${pillarOf(text)} · LIVE`,pillar:pillarOf(text)}}
async function send(text){const clean=text.trim();if(!clean)return;setScreen("dispatch");addMsg("user",clean);$("input").value="";const pending=addMsg("jarvis",hasBrain()?"Linking Grok…":"Triage…");pending.classList.add("pending");try{const out=hasBrain()?await grokDispatch(clean):localDispatch(clean);pending.remove();addMsg("jarvis",out.reply,out.meta);$("status-line").textContent=out.pillar+" in focus. Family still outranks money."}catch(err){pending.remove();const fallback=localDispatch(clean);addMsg("jarvis","Grok failed: "+err.message+"\nFalling back to local rules.\n\n"+fallback.reply,fallback.meta)}}
async function testBrain(){const key=$("api-key").value.trim();const model=$("model").value;if(!key){localStorage.removeItem(KEY_STORE);paintBrain();addMsg("jarvis","Key cleared. Local rules only.","BRAIN local");setScreen("dispatch");return}localStorage.setItem(KEY_STORE,key);localStorage.setItem(MODEL_STORE,model);paintBrain();setScreen("dispatch");addMsg("jarvis","Testing "+model+"…","BRAIN probe");try{const out=await grokDispatch("Confirm you are online as Jarvis. One sentence.");addMsg("jarvis",out.reply,"BRAIN live · "+model);$("brain-note").textContent="Brain live. Probe succeeded."}catch(err){addMsg("jarvis","Probe failed: "+err.message,"BRAIN error");$("brain-note").textContent="Probe failed. Key kept. Check console.x.ai."}}
function drawViz(){const c=$("viz");const ctx=c.getContext("2d");const dpr=Math.min(window.devicePixelRatio||1,2);const w=c.clientWidth;const h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);let t=0;function frame(){ctx.clearRect(0,0,w,h);ctx.strokeStyle="rgba(122,212,240,0.18)";ctx.lineWidth=1;const cx=w/2,cy=h/2+8;for(let i=1;i<=4;i++){ctx.beginPath();ctx.arc(cx,cy,18*i+Math.sin(t/20+i)*3,0,Math.PI*2);ctx.stroke()}ctx.beginPath();ctx.strokeStyle="rgba(122,212,240,0.55)";const sweep=(t/40)%(Math.PI*2);ctx.arc(cx,cy,54,sweep,sweep+0.8);ctx.stroke();ctx.fillStyle="#7ad4f0";ctx.beginPath();ctx.arc(cx,cy,3.2,0,Math.PI*2);ctx.fill();t+=1;requestAnimationFrame(frame)}frame()}
function setupVoice(){const Rec=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Rec){$("mic").addEventListener("click",()=>addMsg("jarvis","Voice engine not available in this browser. Use Safari.","SYSTEM"));return}const rec=new Rec();rec.lang="en-CA";rec.interimResults=false;rec.onresult=e=>send(e.results[0][0].transcript);rec.onend=()=>$("mic").classList.remove("hot");$("mic").addEventListener("click",()=>{$("mic").classList.add("hot");rec.start()})}
document.querySelectorAll(".dock-btn").forEach(b=>b.addEventListener("click",()=>setScreen(b.dataset.screen)));document.querySelectorAll(".pillar").forEach(b=>b.addEventListener("click",()=>{setScreen("dispatch");send("Give me a current standing on the "+b.dataset.pillar+" pillar. Short.")}));$("composer").addEventListener("submit",e=>{e.preventDefault();send($("input").value)});$("brain-form").addEventListener("submit",e=>{e.preventDefault();testBrain()});$("clear-key").addEventListener("click",()=>{localStorage.removeItem(KEY_STORE);$("api-key").value="";paintBrain();addMsg("jarvis","Key cleared. Local rules only.","BRAIN local")});nowClock();setInterval(nowClock,1000);setupVoice();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});boot();
